BOARD=nano_33_iot

USER_LIB_PATH := ${realpath ../libraries}
ARDUINO_LIBS += ambu_common ambu_nano Wire SPI Adafruit-GFX-Library Adafruit_ILI9341 Adafruit_BusIO

include /usr/share/arduino/Arduino.mk

